import { Link } from "wouter";
import { ArrowLeft, Check, ShieldCheck, X } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";

export default function AdminReviews() {
  const { user, loading } = useAuth();
  const { data: pending = [], isLoading } = trpc.commerce.reviews.pending.useQuery(undefined, { enabled: user?.role === "admin" });
  const moderate = trpc.commerce.reviews.moderate.useMutation();
  const decide = async (id: number, status: "approved" | "rejected") => { try { await moderate.mutateAsync({ id, status }); toast(status === "approved" ? "Review approved" : "Review rejected"); } catch { toast.error("We couldn't update this review."); } };
  if (loading) return <main className="min-h-screen bg-[#f7f4ee] p-10 text-[#777269]">Loading moderation queue…</main>;
  if (user?.role !== "admin") return <main className="min-h-screen bg-[#f7f4ee] px-5 py-16"><div className="mx-auto max-w-xl rounded-[2rem] bg-white p-8 text-center shadow-[0_20px_70px_rgba(50,45,35,.08)]"><ShieldCheck className="mx-auto text-[#a6604d]" /><h1 className="mt-5 font-display text-4xl">Admin access required.</h1><p className="mt-3 text-sm leading-6 text-[#777269]">Only approved L-mart administrators can moderate customer reviews.</p><Link href="/" className="button-primary mt-7 inline-flex">Return to shop</Link></div></main>;
  return <main className="min-h-screen bg-[#f7f4ee] text-[#25241f]"><header className="border-b border-[#e1dbd0]"><div className="container flex h-[4.7rem] items-center justify-between"><Link href="/" className="inline-flex items-center gap-2 text-sm text-[#777269]"><ArrowLeft size={16} /> Back to shop</Link><span className="font-display text-3xl tracking-[-.07em]">L-mart<span className="text-[#a6604d]">.</span></span><span className="eyebrow">Moderation</span></div></header><section className="container py-12 sm:py-16"><p className="eyebrow">Trust & safety</p><h1 className="mt-3 font-display text-5xl tracking-[-.06em]">Review queue.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-[#777269]">Approve genuine customer submissions before they appear publicly. No review is created by this screen.</p>{isLoading ? <p className="mt-10 text-sm text-[#777269]">Loading pending reviews…</p> : pending.length ? <div className="mt-10 space-y-4">{pending.map(review => <article key={review.id} className="rounded-2xl border border-[#e0dacf] bg-white p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs uppercase tracking-[.14em] text-[#a6604d]">{review.productHandle}</p><h2 className="mt-1 font-display text-2xl">{review.title || "Untitled review"}</h2></div><span className="text-[#a6604d]">{"★".repeat(review.rating)}{"☆".repeat(5 - review.rating)}</span></div><p className="mt-4 text-sm leading-6 text-[#6d6a61]">{review.body}</p><p className="mt-3 text-xs text-[#9b958a]">Submitted by {review.reviewerName || "L-mart customer"}</p><p className="mt-4 text-xs text-[#777269]">Verified-purchase badges remain disabled until Shopify order/customer reconciliation is connected.</p><div className="mt-5 flex gap-2"><button className="button-primary" onClick={() => decide(review.id, "approved")}><Check size={16} /> Approve</button><button className="button-secondary" onClick={() => decide(review.id, "rejected")}><X size={16} /> Reject</button></div></article>)}</div> : <div className="mt-10 rounded-2xl border border-dashed border-[#d9d3c7] p-12 text-center text-sm text-[#777269]">No pending reviews. New genuine submissions will appear here.</div>}</section></main>;
}
