import { Link } from "wouter";
import { ArrowLeft, Heart, ShoppingBag } from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { useCart } from "@/contexts/CartContext";

const money = (amount: string, currencyCode: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency: currencyCode, maximumFractionDigits: 0 }).format(Number(amount));

export default function Wishlist() {
  const { isAuthenticated } = useAuth();
  const { data: saved = [], isLoading: wishlistLoading } = trpc.commerce.wishlist.list.useQuery(undefined, { enabled: Boolean(isAuthenticated) });
  const { data: products = [], isLoading: productsLoading } = trpc.commerce.products.list.useQuery({ first: 100 }, { enabled: Boolean(isAuthenticated) });
  const remove = trpc.commerce.wishlist.remove.useMutation();
  const { addItem } = useCart();
  const utils = trpc.useUtils();
  const savedProducts = products.filter(product => saved.some(item => item.productHandle === product.handle));
  if (!isAuthenticated) return <main className="min-h-screen bg-[#f7f4ee] px-5 py-16"><div className="mx-auto max-w-xl rounded-[2rem] bg-white p-8 text-center shadow-[0_20px_70px_rgba(50,45,35,.08)] sm:p-12"><Heart className="mx-auto text-[#a6604d]" /><h1 className="mt-5 font-display text-4xl">Your saved edit.</h1><p className="mt-4 text-sm leading-6 text-[#777269]">Sign in to keep favorite products with you across sessions.</p><a href="/api/oauth/login" className="button-primary mt-7 inline-flex">Sign in to save favorites</a></div></main>;
  const removeProduct = async (handle: string) => { try { await remove.mutateAsync({ productHandle: handle }); await utils.commerce.wishlist.list.invalidate(); } catch { toast.error("We couldn't remove that item."); } };
  return <main className="min-h-screen bg-[#f7f4ee] text-[#25241f]"><header className="border-b border-[#e1dbd0]"><div className="container flex h-[4.7rem] items-center justify-between"><Link href="/" className="inline-flex items-center gap-2 text-sm text-[#777269]"><ArrowLeft size={16} /> Back to shop</Link><Link href="/" className="font-display text-3xl tracking-[-.07em]">L-mart<span className="text-[#a6604d]">.</span></Link><Link href="/" className="cart-button" aria-label="Open shopping bag"><ShoppingBag size={17} /></Link></div></header><section className="container py-12 sm:py-16"><p className="eyebrow">Saved for later</p><div className="mt-3 flex items-end justify-between gap-4"><h1 className="font-display text-5xl tracking-[-.06em]">Your wishlist.</h1><span className="text-sm text-[#777269]">{saved.length} saved</span></div>{wishlistLoading || productsLoading ? <div className="mt-10 text-sm text-[#777269]">Loading your saved edit…</div> : savedProducts.length ? <div className="product-grid mt-10">{savedProducts.map(product => { const variant = product.variants[0]; return <article key={product.id} className="group"><Link href={`/product/${product.handle}`}><div className="product-image overflow-hidden rounded-[1.35rem] bg-[#ece8df]">{product.images[0] && <img src={product.images[0].url} alt={product.images[0].altText ?? product.title} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.04]" />}</div><div className="mt-4 flex items-start justify-between gap-3"><div><h2 className="font-medium">{product.title}</h2><p className="mt-1 text-sm text-[#777269]">{product.vendor}</p></div><strong>{variant && money(variant.price.amount, variant.price.currencyCode)}</strong></div></Link><div className="mt-4 flex gap-2"><button className="button-primary flex-1" onClick={async () => { if (variant) { await addItem(variant.id); toast("Added to your bag"); } }}>Add to bag</button><button className="icon-button" aria-label={`Remove ${product.title} from wishlist`} onClick={() => removeProduct(product.handle)}><Heart size={18} fill="currentColor" className="text-[#a6604d]" /></button></div></article>; })}</div> : <div className="mt-10 rounded-2xl border border-dashed border-[#d9d3c7] p-12 text-center"><Heart className="mx-auto text-[#b9b0a3]" /><h2 className="mt-4 font-display text-2xl">Nothing saved yet.</h2><p className="mt-2 text-sm text-[#777269]">Tap the heart on a product to make it part of your edit.</p><Link href="/" className="button-primary mt-6 inline-flex">Discover products</Link></div>}</section></main>;
}
